spring.application.name=StudentManagement
spring.datasource.url=jdbc:mysql://localhost:3306/StudentManagement
spring.datasource.username=root
spring.datasource.password=paotceotI
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# MyBatis ??
# ===============================
# Mapper XML ??????????
mybatis.mapper-locations=classpath:/mapper/*.xml

# DB ????? (snake_case) ? Java ??????? (camelCase) ??????
mybatis.configuration.map-underscore-to-camel-case=true

# MyBatis ???????????
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# ===============================
# JPA (??????????)
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# ===============================
# ?????
# ===============================
server.port=8080